# Generated by Django 5.2.5 on 2025-08-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_job_apply_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
